# Generated by Django 4.2.3 on 2023-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pat_Name", models.CharField(max_length=50)),
                ("Pat_surname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("staff_number", models.PositiveIntegerField()),
                ("id_number", models.PositiveIntegerField()),
                ("specialization", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Dentist", "Dentistry"),
                            ("Cardiologist", "Cardiology"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
