# Generated by Django 4.2.6 on 2023-10-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_Name', models.CharField(max_length=50, unique=True)),
                ('Description', models.CharField(max_length=190, unique=True)),
                ('Phone', models.CharField(max_length=13, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Location', models.CharField(max_length=100, unique=True)),
                ('Date_Added', models.DateTimeField()),
                ('Date_Update', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_number', models.PositiveIntegerField()),
                ('id_number', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Dentist', 'Dentistry'), ('Cardiologist', 'Cardiology')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fnames', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Staff_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('Role', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Rates', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('NumOfRates', models.IntegerField(default=0)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_names', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Phn_no', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Date_Added', models.DateTimeField()),
                ('Date_Updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Available', models.CharField(max_length=100)),
                ('Identifier', models.CharField(max_length=100)),
                ('Date_Reg', models.DateTimeField()),
                ('Date_Updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.IntegerField()),
                ('Feedback', models.CharField(max_length=100)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.employees')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptoms', models.CharField(max_length=150)),
                ('Diagnosis', models.CharField(max_length=150)),
                ('Doc_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.employees')),
                ('Pat_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.patients')),
            ],
        ),
        migrations.CreateModel(
            name='AppovedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('CellNumber', models.CharField(max_length=15, unique=True)),
                ('EmailAddress', models.CharField(max_length=50, unique=True)),
                ('SetByUser', models.BooleanField(default=False)),
                ('last_login', models.CharField(max_length=50, unique=True)),
                ('authenticated', models.BooleanField(default=False)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.employees', unique=True)),
                ('UserPrivilege', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.userprivileges')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Attended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=100)),
                ('Description', models.CharField(max_length=150)),
                ('Date_set', models.DateTimeField()),
                ('App_date', models.DateTimeField()),
                ('Date_updated', models.DateTimeField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.employees')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patients')),
            ],
        ),
    ]
