# Generated by Django 3.2.18 on 2023-10-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customusers',
            name='UserPrivilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.userprivileges'),
        ),
    ]
