# Generated by Django 4.2.3 on 2023-08-18 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Dep_Name", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=10000)),
                ("Phone", models.CharField(max_length=13)),
                ("Email", models.CharField(max_length=100)),
                ("Location", models.CharField(max_length=100)),
                ("Date_Added", models.DateTimeField()),
                ("Date_Update", models.DateTimeField()),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fnames", models.CharField(max_length=100)),
                ("Lname", models.CharField(max_length=100)),
                ("DOB", models.DateField()),
                ("Staff_number", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("Role", models.CharField(max_length=100)),
                ("Specialization", models.CharField(max_length=100)),
                (
                    "Department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("F_names", models.CharField(max_length=100)),
                ("L_names", models.CharField(max_length=100)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=100
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Address", models.CharField(max_length=100)),
                ("Phn_no", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Date_Added", models.DateTimeField()),
                ("Date_Updated", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type", models.CharField(max_length=100)),
                ("Available", models.CharField(max_length=100)),
                ("Identifier", models.CharField(max_length=100)),
                ("Date_Reg", models.DateTimeField()),
                ("Date_Updated", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="Pat_Name",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="Pat_surname",
        ),
        migrations.AddField(
            model_name="appointment",
            name="App_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="App_status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Attended"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="Date_set",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 18, 20, 28, 31, 867919, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="Description",
            field=models.CharField(default="N/A", max_length=2500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptoms", models.CharField(max_length=2500)),
                ("Diagnosis", models.CharField(max_length=10000)),
                (
                    "Doc_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.employees",
                    ),
                ),
                (
                    "Pat_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.patients",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="Doctor_Id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="hospital.employees",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="Pat_ID",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.patients",
            ),
            preserve_default=False,
        ),
    ]
