# Generated by Django 4.2.3 on 2023-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_department_employees_patients_rooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="Dep_Name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="Description",
            field=models.CharField(max_length=10000, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="Email",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="Location",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="Phone",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
