# Generated by Django 4.2.3 on 2023-08-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_department_dep_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patients",
            old_name="Date",
            new_name="DOB",
        ),
    ]
