# Generated by Django 3.2.18 on 2023-10-14 07:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_username_customusers_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
