# Generated by Django 3.2.18 on 2023-10-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_customusers_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
            ],
        ),
    ]
