# Generated by Django 4.2.3 on 2023-08-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_alter_patients_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patients",
            old_name="L_names",
            new_name="L_name",
        ),
    ]
