# Generated by Django 4.2.3 on 2023-08-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_rename_l_names_patients_l_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="Doctor_Id",
            new_name="Doctor",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="Pat_ID",
            new_name="Patient",
        ),
    ]
