# Generated by Django 4.2.3 on 2023-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0007_rename_doctor_id_appointment_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="App_status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Attended"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=100,
            ),
        ),
    ]
