# Generated by Django 3.2.18 on 2023-10-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appovedusers_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appovedusers',
            name='key',
        ),
    ]
