# Generated by Django 4.2.3 on 2023-08-19 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0008_alter_appointment_app_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="Date_updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 19, 20, 45, 53, 906081, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
