# Generated by Django 4.2.3 on 2023-08-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0009_appointment_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="Rates",
            field=models.IntegerField(default=0.0),
        ),
    ]
