# Generated by Django 3.2.18 on 2023-10-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_appovedusers_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUsers',
        ),
    ]
