# Generated by Django 4.2.3 on 2023-08-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0010_employees_rates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rate", models.IntegerField()),
                ("Feedback", models.CharField(max_length=15000)),
                (
                    "Employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.employees",
                    ),
                ),
                (
                    "Patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.patients",
                    ),
                ),
            ],
        ),
    ]
