# Generated by Django 4.2.3 on 2023-09-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0011_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=20)),
                ("CellNumber", models.CharField(max_length=15)),
                ("EmailAddress", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=100)),
                ("SetByUser", models.BooleanField(default=False)),
                ("UserPrivilege", models.CharField(max_length=50)),
            ],
        ),
    ]
