# Generated by Django 4.2.3 on 2023-09-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0012_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="NumOfRates",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="employees",
            name="Rates",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
